### PR TITLE
Modify validation of names and related tests

### LINKED ISSUE #22: Bug: Adding names with / or \
Certian valid names can contain `/ ` or `\` characters. Current code rejects all special characters in name. Modify behaviour to make exceptions to this rule such that these characters are allowed provided they do not occur at the start or end of the String. 

Invalid examples:

- `/Name`
- `Name/`

Valid examples:

- `N/ame`
- `Na/me`

### LINKED ISSUE #36: Change validation of names
As per our feature specifications, names should only include letters and spaces. Current implementation allows for all alphanumeric characters, as well as undesirable inputs such as long series of spaces, which needs to be fixed.

### PR DESCRIPTION
**Pull request by Vision-2000**
close #22 
close #36 

Name format is now as follows:
Alphabet, repeat :special character followed immediately by alphabet OR just alphabet

Special characters allowed: ` ` `\` `/` `-`

### CODE REVIEW

File: src/test/java/seedu/address/model/patient/PatientTest.java [hunk 1]
```diff
@@ -38,11 +38,6 @@ public void isSamePerson() {
         // name differs in case, all other attributes same -> returns false
         Patient editedBob = new PatientBuilder(BOB).withName(VALID_NAME_BOB.toLowerCase()).build();
         assertFalse(BOB.isSamePatient(editedBob));
-
-        // name has trailing spaces, all other attributes same -> returns false
-        String nameWithTrailingSpaces = VALID_NAME_BOB + " ";
-        editedBob = new PatientBuilder(BOB).withName(nameWithTrailingSpaces).build();
-        assertFalse(BOB.isSamePatient(editedBob));
```
Comment (jskimdev) [inline src/test/java/seedu/address/model/patient/PatientTest.java:45]: why is this testcase being removed?

File: src/test/java/seedu/address/model/patient/NameTest.java [hunk 2]
```diff
@@ -27,15 +27,14 @@ public void isValidName() {
...
         assertFalse(Name.isValidName("")); // empty string
         assertFalse(Name.isValidName(" ")); // spaces only
-        assertFalse(Name.isValidName("^")); // only non-alphanumeric characters
-        assertFalse(Name.isValidName("peter*")); // contains non-alphanumeric characters
+        assertFalse(Name.isValidName("^")); // only non-alphabets
+        assertFalse(Name.isValidName("peter*")); // contains disallowed character
 
         // valid name
         assertTrue(Name.isValidName("peter jack")); // alphabets only
-        assertTrue(Name.isValidName("12345")); // numbers only
```
Comment (jeong-jaeho) [inline src/test/java/seedu/address/model/patient/NameTest.java:35]: Why is this case being removed?

**Review by jeong-jaeho — COMMENTED** [review]
LGTM except some minor details

File: src/test/java/seedu/address/model/patient/NameTest.java (hunk 2 above)
Comment (Vision-2000) [reply src/test/java/seedu/address/model/patient/NameTest.java:35]: Because we're disallowing numbers. If you mean that it should be moved to a negative test, I could do that

**Review by jeong-jaeho — COMMENTED** [review]
LGTM.
